# Generated by Django 5.1.7 on 2025-03-26 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('setor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_aquisicao', models.DateField()),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('manutencao', 'Em Manutenção'), ('baixado', 'Baixado')], default='ativo', max_length=20)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patrimonio.categoria')),
                ('localizacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patrimonio.localizacao')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patrimonio.responsavel')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True)),
                ('localizacao_anterior', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origem', to='patrimonio.localizacao')),
                ('localizacao_nova', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destino', to='patrimonio.localizacao')),
                ('patrimonio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrimonio.patrimonio')),
                ('responsavel_anterior', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsavel_anterior', to='patrimonio.responsavel')),
                ('responsavel_novo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsavel_novo', to='patrimonio.responsavel')),
            ],
        ),
    ]
